/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_aritmatika;

/**
 *
 * @author Asus
 */
public class Aritmatika extends javax.swing.JFrame {
    
    String jns = "";
    int jml;

    /**
     * Creates new form Aritmatika
     */
    public Aritmatika() {
        initComponents();
        setJenis();
        getJumlah();
        jns = null;
        panel.hide();
        bil1.setVisible(false);
        bil2.setVisible(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SetJenis = new javax.swing.JComboBox();
        panel = new javax.swing.JPanel();
        jmlBil = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        b4 = new javax.swing.JLabel();
        hasil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tvhasil = new javax.swing.JTextArea();
        ket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 10, 230, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 60, 110, 30);

        SetJenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Salah Satu --", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian", " " }));
        SetJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetJenisActionPerformed(evt);
            }
        });
        jPanel2.add(SetJenis);
        SetJenis.setBounds(160, 60, 180, 30);

        panel.setBackground(new java.awt.Color(204, 204, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operator"));
        panel.setLayout(null);

        jmlBil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", " " }));
        jmlBil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlBilActionPerformed(evt);
            }
        });
        panel.add(jmlBil);
        jmlBil.setBounds(150, 70, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Jumlah Bilangan");
        panel.add(jLabel3);
        jLabel3.setBounds(40, 70, 110, 30);

        b1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b1.setText("Bilangan 1");
        panel.add(b1);
        b1.setBounds(40, 110, 110, 30);

        b2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b2.setText("Bilangan 2");
        panel.add(b2);
        b2.setBounds(40, 150, 110, 30);

        b3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b3.setText("Bilangan 3");
        panel.add(b3);
        b3.setBounds(40, 190, 110, 30);
        panel.add(bil1);
        bil1.setBounds(150, 110, 180, 30);
        panel.add(bil2);
        bil2.setBounds(150, 150, 180, 30);
        panel.add(bil3);
        bil3.setBounds(150, 190, 180, 30);
        panel.add(bil4);
        bil4.setBounds(150, 230, 180, 30);

        b4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        b4.setText("Bilangan 4");
        panel.add(b4);
        b4.setBounds(40, 230, 110, 30);

        hasil.setText("HITUNG");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        panel.add(hasil);
        hasil.setBounds(140, 280, 100, 30);

        tvhasil.setColumns(20);
        tvhasil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tvhasil.setRows(5);
        jScrollPane1.setViewportView(tvhasil);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(40, 320, 290, 90);

        ket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panel.add(ket);
        ket.setBounds(150, 20, 130, 30);

        jPanel2.add(panel);
        panel.setBounds(10, 110, 380, 440);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 560);

        setBounds(0, 0, 416, 596);
    }// </editor-fold>//GEN-END:initComponents

    private void SetJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetJenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_SetJenisActionPerformed
            public void setJenis(){
                if(SetJenis.getSelectedItem().equals("Penjumlahan")){
                    jns = "Penjumlahan";
                    ket.setText("Penjumlahan");
                    panel.setVisible(true);
                    jmlBil.setEnabled(true);
                }
                else if(SetJenis.getSelectedItem().equals("Pengurangan")){
                    jns = "Pengurangan";
                    ket.setText("Pengurangan");
                    panel.setVisible(true);
                    jmlBil.setEnabled(true);
                }
                else if(SetJenis.getSelectedItem().equals("Perkalian")){
                    jns = "Perkalian";
                    ket.setText("Perkalian");
                    panel.setVisible(true);
                    jmlBil.setEnabled(true);
                }
                else if(SetJenis.getSelectedItem().equals("Pembagian")){
                    jns = "Pembagian";
                    ket.setText("Pembagian");
                    panel.setVisible(true);
                    jmlBil.setEnabled(true);
                }
            }
            
       
    
    private void jmlBilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlBilActionPerformed
        // TODO add your handling code here:
            getJumlah();
    }//GEN-LAST:event_jmlBilActionPerformed

            public void getJumlah(){
                if(jmlBil.getSelectedItem().equals("2")){
                    bil1.setVisible(true);
                    bil2.setVisible(true);
                    bil3.setVisible(false);
                    bil4.setVisible(false);
                    b1.setVisible(true);
                    b2.setVisible(true);
                    b3.setVisible(false);
                    b4.setVisible(false);
                    jml=2;
                }
                else if(jmlBil.getSelectedItem().equals("3")){
                    bil1.setVisible(true);
                    bil2.setVisible(true);
                    bil3.setVisible(true);
                    bil4.setVisible(false);
                    b1.setVisible(true);
                    b2.setVisible(true);
                    b3.setVisible(true);
                    b4.setVisible(false);
                    jml=3;
                }
                else if(jmlBil.getSelectedItem().equals("4")){
                    bil1.setVisible(true);
                    bil2.setVisible(true);
                    bil3.setVisible(true);
                    bil4.setVisible(true);
                    b1.setVisible(true);
                    b2.setVisible(true);
                    b3.setVisible(true);
                    b4.setVisible(true);
                    jml=4;
                }
               
            }
    
    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());
        
        
        if(jns.equals("Penjumlahan")) {
            if(jml == 2) {
                hsl = a1+a2;
                tvhasil.setText(""+a1+" + "+a2+" = "+ hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1+a2+a3;
                tvhasil.setText(""+a1+" + "+a2+" + "+a3+" = "+ hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1+a2+a3+a4;
                tvhasil.setText(""+a1+" + "+a2+" + "+a3+" + "+a4+" = "+ hsl);
            } 
        }
        else if(jns.equals("Pengurangan")) {
            if(jml == 2) {
                hsl = a1-a2;
                tvhasil.setText(""+a1+" - "+a2+" = "+ hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1-a2-a3;
                tvhasil.setText(""+a1+" - "+a2+" - "+a3+" = "+ hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1-a2-a3-a4;
                tvhasil.setText(""+a1+" - "+a2+" - "+a3+" - "+a4+" = "+ hsl);
            } 
        }
        else if(jns.equals("Perkalian")) {
            if(jml == 2) {
                hsl = a1*a2;
                tvhasil.setText(""+a1+" * "+a2+" = "+ hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1*a2*a3;
                tvhasil.setText(""+a1+" * "+a2+" * "+a3+" = "+ hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1*a2*a3*a4;
                tvhasil.setText(""+a1+" * "+a2+" * "+a3+" * "+a4+" = "+ hsl);
            } 
        }
        else if(jns.equals("Pembagian")) {
            if(jml == 2) {
                hsl = a1/a2;
                tvhasil.setText(""+a1+" / "+a2+" = "+ hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1/a2/a3;
                tvhasil.setText(""+a1+" / "+a2+" / "+a3+" = "+ hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1/a2/a3/a4;
                tvhasil.setText(""+a1+" / "+a2+" / "+a3+" / "+a4+" = "+ hsl);
            } 
        }
    }//GEN-LAST:event_hasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox SetJenis;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JButton hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jmlBil;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JTextArea tvhasil;
    // End of variables declaration//GEN-END:variables

}
